# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-10 16:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='description',
            field=models.CharField(default='enter description', max_length=255),
        ),
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('1', 'Todo'), ('2', 'Doing'), ('3', 'Done')], default='choose status', max_length=1),
        ),
        migrations.AddField(
            model_name='todo',
            name='title',
            field=models.CharField(default='enter title', max_length=100),
        ),
        migrations.AddField(
            model_name='todo',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
